spring:
  application:
    name: microservice-discovery-eureka-ha
  profiles:
    active: peer1
  cloud:
    inetutils:
      use-only-site-local-interfaces: true  #只使用本地地址
      preferred-networks:      #指定使用的网络地址
        - 192.168
        - 10.0
      ignored-interfaces:
        - docker0       # 忽略docker0网卡
        - veth.*        # 忽略 veth开头的网卡

security:
  basic:
    enabled: true
  user:
    name: user
    password: pwd123

---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false             # 关闭注册中心的保护机制，Eureka 会统计15分钟之内心跳失败的比例低于85%将会触发保护机制，不剔除服务提供者，如果关闭服务注册中心将不可用的实例正确剔除
  instance:
    hostname: peer1                               # 指定当profile=peer1时，主机名是peer1
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://user:pwd123@peer2:8762/eureka/      # 将自己注册到peer2这个Eureka上面去
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    ip-address: 10.16.8.210   #指定IP地址
    hostname: peer2
  client:
    healthcheck:
      enabled: true       #开启健康检查
    serviceUrl:
      defaultZone: http://user:pwd123@peer1:8761/eureka/
  server:
    enable-self-preservation: true        #Eureka 自我保护模式开关