server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    passsword: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:pwd123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true


#turbine:
#  app-config: microservice-consumer-movie,microservice-consumer-movie-test
#  cluster-name-expression: "'default'"

