server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie

#server:
#  port: 8011
#spring:
#  application:
#    name: microservice-consumer-movie-test

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:pwd123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

microservice-provider-user:           # 使用配置文件的方式修改该微服务的Ribbon客户端的负载均衡规则   <clientName>.ribbon.XXX
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#microservice-provider-user:
#  ribbon:
#    listOfServers: localhost:8000,localhost:8001   #不使用Eureka，只使用Ribbon来实现负载均衡
